### ISSUE TITLE
How about making a bower package?

### ISSUE THREAD

**Issue by Hiraqui** [tennisgent/quickmock#19]
It would be great since we use bower to install plugins on our app.
Thank you!
Great work btw

**Comment by tennisgent** [comment]
As per [this article](https://gofore.com/stop-using-bower/) and [this article](https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb) and [this article](https://grobmeier.solutions/bower-github-community-18112015.html) (as well as many others), the industry is moving away from bower and therefore I don't see the need to publish this there. I would suggest you and your team move to npm or [yarn](https://github.com/yarnpkg/yarn).
